@startuml
'https://plantuml.com/class-diagram

hide empty fields
hide empty methods

    class Document {
        문서 = 문장들의 모임
        --
        - List<ISentence> sentences
        --
        + void render()
    }


    interface IFormat {
        + void render()
        + void loadRenderData()
    }

    class FontFamilyFormat {
        - String fontFamilyName
        - String fontFamilyPath
        - byte[] renderData
    }

    class FontStyleFormat {
        - String fontStyleName
        - byte[] renderData
    }

    class Sentence {
        - FontFamilyFormat fontFamilyFormat
        - FontStyleFormat fontStyleFormat
        - int fontSize
        - String content
        --
        + void render()
    }

    Document *-u-> Sentence

    Sentence .u.> FontFamilyFormat
    Sentence .u.> FontStyleFormat

    FontStyleFormat .up.|> IFormat
    FontFamilyFormat .up.|> IFormat

class FontFormatFactory<<Singleton>> {

    - Hashmap<FontFormatType, HashMap<String, IFormat>> formats
    --
    + void addFormat(FontFormatType, IFormat format)
    + IFormat getFormat(FontFormatType, String formatName)
}

enum FontFormatType {
    FONT_FAMILY
    FONT_STYLE
}

FontFormatFactory *-l-> IFormat
FontFormatFactory -d-> FontFormatType


@enduml