@startuml
'https://plantuml.com/class-diagram

!theme reddress-darkgreen

hide empty fields
hide empty methods

package visitor {
    abstract ShapeVisitor<<Visitor>> {
        void visit(Circle)
        void visit(Hexagon)
        void visit(Rectangle)
    }

    abstract PositioningShapeVisitor {
        - int x
        - int y
    }

    PositioningShapeVisitor .u.|> ShapeVisitor
    CirclePositioningShapeVisitor .u.|> PositioningShapeVisitor
    HaxagonPositioningShapeVisitor .r.|> PositioningShapeVisitor
    RectanglePositioningShapeVisitor .r.|> PositioningShapeVisitor
    PrintingInfoShapeVisitor .u.|> ShapeVisitor
    RectanglePositioningShapeVisitor .u.|> HaxagonPositioningShapeVisitor #transparent
}

package shape {
    abstract Shape<<Element>> {
        - int x
        - int y
        --
        + abstract void accept(Visitor)
    }

   class Circle {
        + void accept(Visitor)
   }

   class Rectangle {
       + void accept(Visitor)
   }

   class Hexagon {
       + void accept(Visitor)
   }

    Circle .d.|> Shape
    Hexagon .d.|> Shape
    Rectangle .d.|> Shape
}

ShapeVisitor .u.> Shape
Shape .d.> ShapeVisitor







@enduml